---
title: "maftools para descrição da rede regulatoria do cftr"
data: 08/04
autor: Camila Sinimbú Forte
---


```{r}
library(maftools) 
stomach = read.maf(maf = 'GC_TCGA_maf.txt')
pancreas = read.maf(maf = 'PANCREAS_TCGA_maf.txt')
lung = read.maf(maf = 'LUNG_TCGA_maf.txt')
```

```{r}
plotmafSummary(stomach, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
plotmafSummary(pancreas, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
plotmafSummary(lung, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)

```




```{r}
oncoplot(maf = stomach, top = 5)
oncoplot(maf = pancreas, top = 5)
oncoplot(maf = lung, top = 5)
```


```{r}
#pdf(file = "cobarplot.pdf")

coBarplot(m1 = stomach, m2 = pancreas, m1Name = "stomach", m2Name = "pancreas")

#dev.off()
```



```{r}
somaticInteractions(maf = stomach, top = 25, pvalue = c(0.05))
somaticInteractions(maf = pancreas, top = 25, pvalue = c(0.05))
somaticInteractions(maf = lung, top = 25, pvalue = c(0.05))

```


